apiVersion: v1
kind: ConfigMap
metadata:
  name: home-furniture-config
data:
  CATEGORY: "Home & Furniture"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-furniture-deployment
  labels:
    app: home-furniture
spec:
  replicas: 2
  selector:
    matchLabels:
      app: home-furniture
  template:
    metadata:
      labels:
        app: home-furniture
    spec:
      containers:
      - name: home-furniture
        image: your-registry/ecom-home-furniture:latest  # Replace with your Docker image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        envFrom:
        - configMapRef:
            name: home-furniture-config
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: home-furniture-service
spec:
  selector:
    app: home-furniture
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP